const wordList = [
    { word: "javascript", hint: "A programming language for web development." },
    { word: "elephant", hint: "A large mammal with tusks and a trunk." },
    { word: "pineapple", hint: "A tropical fruit with a spiky skin." },
    { word: "mountain", hint: "A large landform that rises prominently above its surroundings." },
    { word: "keyboard", hint: "An input device used to type characters into a computer." },
    { word: "sunflower", hint: "A tall plant with large yellow flowers and edible seeds." },
    { word: "guitar", hint: "A musical instrument with strings, often played by strumming or plucking." },
    { word: "bicycle", hint: "A two-wheeled vehicle powered by pedals." },
    { word: "ocean", hint: "A vast expanse of saltwater covering most of the Earth's surface." },
    { word: "astronaut", hint: "A person trained to travel or work in outer space." },
    { word: "umbrella", hint: "A device used for protection against rain or sunlight." },
    { word: "dragon", hint: "A mythical, fire-breathing creature often depicted with wings and scales." },
    { word: "jungle", hint: "A dense, overgrown area of land, typically in a tropical rainforest." },
    { word: "moonlight", hint: "The light from the moon that illuminates the night sky." },
    { word: "puzzle", hint: "A game, toy, or problem designed to test ingenuity or knowledge." },
    { word: "whale", hint: "A large marine mammal with a streamlined body and a blowhole." },
    { word: "island", hint: "A piece of land surrounded by water, smaller than a continent." },
    { word: "fireworks", hint: "Explosive devices producing a burst of light and sound for celebration." },
    { word: "chocolate", hint: "A sweet food product made from roasted and ground cacao seeds." },
    { word: "telescope", hint: "An optical instrument for viewing distant objects in space." },
    { word: "rainbow", hint: "A meteorological phenomenon with a spectrum of light in the sky." },
    { word: "robot", hint: "A machine capable of carrying out tasks autonomously or with remote control." },
    { word: "volcano", hint: "A mountain that erupts with lava, ash, and gases." },
    { word: "penguin", hint: "A flightless bird native to the Southern Hemisphere, known for its tuxedo-like appearance." },
    { word: "cactus", hint: "A succulent plant adapted to hot, dry climates, often with spines." },
    { word: "whisper", hint: "Speaking in a hushed or soft tone to avoid being overheard." },
    { word: "festival", hint: "A celebration or series of events often marked by feasting and cultural activities." },
    { word: "zeppelin", hint: "A type of rigid airship named after the German Count Ferdinand von Zeppelin." },
    { word: "paradise", hint: "An ideal or idyllic place or state of perfection and happiness." },
    { word: "quasar", hint: "An extremely luminous celestial object, powered by a massive black hole." },
    { word: "safari", hint: "An expedition to observe or hunt animals in their natural habitat." },
    { word: "tornado", hint: "A rapidly rotating column of air extending from a thunderstorm to the ground." },
    { word: "carousel", hint: "A rotating platform with seats for amusement rides." },
    { word: "waffle", hint: "A batter-based dish cooked between two patterned plates, often eaten for breakfast." },
    { word: "alchemy", hint: "An ancient practice that aimed to transform base metals into gold and discover the elixir of life." },
    { word: "cathedral", hint: "A large and important church that is the seat of a bishop." },
    { word: "whirlwind", hint: "A rapidly rotating column of air, often in the form of a destructive tornado." },
    { word: "glacier", hint: "A large, slow-moving mass of ice formed by the accumulation and compaction of snow." },
    { word: "oasis", hint: "A fertile area in a desert with water and vegetation." },
    { word: "echo", hint: "A sound that is reflected off a surface and heard again." },
    { word: "treasure", hint: "Valuables, riches, or wealth, often hidden or buried." },
    { word: "galaxy", hint: "A vast system of stars, gas, and dust held together by gravity." },
    { word: "whistle", hint: "A small wind instrument that produces a clear sound when blown." },
    { word: "toucan", hint: "A colorful bird native to tropical regions, known for its large and colorful bill." },
    { word: "quicksand", hint: "A soft, wet, or loose sand that yields easily to pressure and sucks in anything resting on or falling into it." }
  ];